<?php

/**
 * @file
 * Typogrify: Brings typographical refinemnts to drupal
 *
 * Hook together all the typogrify components.
 */

/**
 * Implements hook_filter_info().
 */
function typogrify_filter_info() {
  return array(
    'typogrify' => array(
      'title' => t('Typogrify'),
      'description' => t('Adds typographic refinements.'),
      'process callback' => '_typogrify_process',
      'settings callback' => '_typogrify_settings',
      'default settings' => array(
        'smartypants_enabled' => 1,
        'smartypants_hyphens' => 3,
        'wrap_ampersand' => 1,
        'widont_enabled' => 1,
        'wrap_caps' => 1,
        'wrap_initial_quotes' => 1,
        'long_s' => 0,
        'ligatures' => array(),
        'arrows' => array(),
        'quotes' => array(),
      ),
      'tips callback' => '_typogrify_filter_tips',
    ),
  );
}

/**
 * Filter tips callback for Typogrify filter.
 */
function _typogrify_filter_tips($filter, $format, $long) {
  if ($long) {
    module_load_include('php', 'typogrify', 'unicode-conversion');
    $opts = "";
    // Build a list of quotation marks to convert.
    foreach (unicode_conversion_map('quotes') as $ascii => $unicode) {
      if ($filter->settings['quotes'][$ascii]) {
        $opts .= '<li>' . t('Converts <code>!ascii</code> to !unicode', array(
          '!ascii' => $ascii,
          '!unicode' => $unicode,
        )) . "</li>\n";
      }
    }
    $output = t('Typogrify.module brings the typographic refinements of Typogrify to Drupal.<ul>
<li>Wraps ampersands (the &ldquo;&amp;&rdquo; character) with &lt;span class=\"amp\"&gt;&amp;&lt;/span&gt;.</li>
<li>Prevents single words from wrapping onto their own line using Shaun Inman\'s Widont technique.</li>
<li>Converts straight quotation marks to typographer\'s quotation marks, using SmartyPants.</li>
<li>Converts multiple hyphens to en dashes and em dashes (according to your preferences), using SmartyPants.</li>
<li>Wraps multiple capital letters with &lt;span class=\"caps\"&gt;CAPS&lt;/span&gt;.</li>
<li>Wraps initial quotation marks with &lt;span class=\"quo\"&gt;&lt;/span&gt; or &lt;span class=\"dquo\"&gt;&lt;/span&gt;.</li>
<li>Adds a css style sheet that uses the &lt;span&gt; tags to substitute a showy ampersand in headlines, switch caps to small caps, and hang initial quotation marks.</li>!enabledOptions</ul>', array('!enabledOptions' => $opts));
  }
  else {
    $output = t('Typographic refinements will be added.');
  }

  return $output;
}

/**
 * Implements hook_init().
 */
function typogrify_init() {
  drupal_add_css(drupal_get_path('module', 'typogrify') . '/typogrify.css');
}

/**
 * Processing function to apply the Typogrify filters.
 *
 * @param string $text
 *   The text to apply the filter on.
 * @param array $filter
 *   The options set for this filter.
 * @param integer $format
 *   ID if the input format whose settings to use when applying the filters.
 * @param string $langcode
 *   The language code of this field.
 *
 * @return string
 *   The filtered text.
 */
function _typogrify_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  $characters_to_convert = array();
  $ctx = array();
  if ($langcode == 'und') {
    global $language;
    $ctx['langcode'] = $language->language;
  }
  else {
    $ctx['langcode'] = $langcode;
  }
  // Load Helpers.
  module_load_include('class.php', 'typogrify');
  module_load_include('php', 'typogrify', 'unicode-conversion');
  module_load_include('php', 'typogrify', 'smartypants');

  // Wrap ampersands.
  if ($filter->settings['wrap_ampersand']) {
    $text = Typogrify::amp($text);
  }

  // Remove widows.
  if ($filter->settings['widont_enabled']) {
    $text = Typogrify::widont($text);
  }

  // Smartypants formatting.
  if ($filter->settings['smartypants_enabled']) {
    $text = SmartyPants($text, $filter->settings['smartypants_hyphens'], $ctx);
  }

  // Wrap caps.
  if ($filter->settings['wrap_caps']) {
    $text = Typogrify::caps($text);
  }

  // Wrap initial quotes.
  if ($filter->settings['wrap_initial_quotes']) {
    $text = Typogrify::initial_quotes($text);
  }

  // Build a list of ligatures to convert.
  foreach (unicode_conversion_map('ligature') as $ascii => $unicode) {
    if ($filter->settings['ligatures'][$ascii]) {
      $characters_to_convert[] = $ascii;
    }
  }

  // Build a list of arrows to convert.
  foreach (unicode_conversion_map('arrow') as $ascii => $unicode) {
    if ($filter->settings['arrows'][$ascii]) {
      $characters_to_convert[] = $ascii;
    }
  }

  // Build a list of quotation marks to convert.
  foreach (unicode_conversion_map('quotes') as $ascii => $unicode) {
    if ($filter->settings['quotes'][$ascii]) {
      $characters_to_convert[] = $ascii;
    }
  }

  // Convert ligatures and arrows.
  if (count($characters_to_convert) > 0) {
    $text = convert_characters($text, $characters_to_convert);
  }

  return $text;
}


/**
 * Typogrify filter settings form.
 *
 * @param array $form
 *   The prepopulated form array of the filter administration form.
 * @param array $form_state
 *   The state of the (entire) configuration form.
 * @param object $filter
 *   The filter object containing the current settings for the given format, in
 *   $filter->settings.
 * @param integer $format
 *   ID if the input format to generate a settings form for.
 *
 * @return array
 *   Form API array containing our settings form.
 */
function _typogrify_settings($form, &$form_state, $filter, $format, $defaults, $filters) {
  module_load_include('class.php', 'typogrify');
  module_load_include('php', 'typogrify', 'unicode-conversion');
  module_load_include('php', 'typogrify', 'smartypants');

  // Add our default settings to the array if they are not present.
  $filter->settings += array(
    'smartypants_enabled' => 1,
    'smartypants_hyphens' => 2,
    'wrap_ampersand' => 1,
    'widont_enabled' => 1,
    'wrap_caps' => 1,
    'wrap_initial_quotes' => 1,
    'ligatures' => array(),
    'arrows' => array(),
    'quotes' => array(),
  );

  $form = array();

  $form['help'] = array(
    '#type' => 'markup',
    '#value' => '<p>' . t("Enable the following typographic refinements:") . '</p>',
  );

  // Smartypants settings.
  $form['smartypants_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use typographers quotation marks and dashes (!smartylink)', array(
      '!smartylink' => l('SmartyPants', 'http://daringfireball.net/projects/smartypants/'),
    )),
    '#default_value' => $filter->settings['smartypants_enabled'],
  );

  // Smartypants hyphenation settings.
  // Uses the same values as the parse attributes in the SmartyPants
  // function (@see SmartyPants in smartypants.php)
  $form['smartypants_hyphens'] = array(
    '#type' => 'select',
    '#title' => t('Hyphenation settings for SmartyPants'),
    '#default_value' => $filter->settings['smartypants_hyphens'],
    '#options' => array(
      1 => t('“--” for em-dashes; no en-dash support'),
      3 => t('“--” for em-dashes; “---” for en-dashes'),
      2 => t('“---” for em-dashes; “--” for en-dashes'),
    ),
  );

  // Wrap ampersand settings.
  $form['wrap_ampersand'] = array(
    '#type' => 'checkbox',
    '#title' => t('Wrap ampersands'),
    '#default_value' => $filter->settings['wrap_ampersand'],
  );

  // Remove widows settings.
  $form['widont_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Remove widows'),
    '#default_value' => $filter->settings['widont_enabled'],
  );

  // Wrap caps settings.
  $form['wrap_caps'] = array(
    '#type' => 'checkbox',
    '#title' => t('Wrap caps'),
    '#default_value' => $filter->settings['wrap_caps'],
  );

  // Wrap initial quotes settings.
  $form['wrap_initial_quotes'] = array(
    '#type' => 'checkbox',
    '#title' => t('Wrap quotation marks'),
    '#default_value' => $filter->settings['wrap_initial_quotes'],
  );

  // Ligature conversion settings.
  $ligature_options = array();
  foreach (unicode_conversion_map('ligature') as $ascii => $unicode) {
    $ligature_options[$ascii] = t('Convert <code>@ascii</code> to !unicode', array(
      '@ascii' => $ascii,
      '!unicode' => $unicode,
    ));
  }

  $form['ligatures'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Ligatures'),
    '#options' => $ligature_options,
    '#default_value' => $filter->settings['ligatures'],
  );

  // Arrow conversion settings.
  $arrow_options = array();
  foreach (unicode_conversion_map('arrow') as $ascii => $unicode) {
    $arrow_options[$ascii] = t('Convert <code>@ascii</code> to !unicode', array(
      '@ascii' => $ascii,
      '!unicode' => $unicode,
    ));

  }

  $form['arrows'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Arrows'),
    '#options' => $arrow_options,
    '#default_value' => $filter->settings['arrows'],
  );

  // Quotes conversion settings.
  $quotes_options = array();
  foreach (unicode_conversion_map('quotes') as $quotes => $unicode) {
    $quotes_options[$quotes] = t('Convert <code>@ascii</code> to !unicode', array(
      '@ascii' => $quotes,
      '!unicode' => $unicode,
    ));
  }

  $form['quotes'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Quotes'),
    '#options' => $quotes_options,
    '#default_value' => $filter->settings['quotes'],
  );
  // Version Information Settings.
  $version_strings = array();
  $version_strings[] = t('SmartyPants PHP version: !version', array(
    '!version' => l(SMARTYPANTS_PHP_VERSION, 'http://www.michelf.com/projects/php-smartypants/'),
  ));
  $version_strings[] = t('PHP Typogrify Version: !version', array(
    '!version' => l('1.0', 'http://blog.hamstu.com/'),
  ));

  $form['info']['typogrify_status'] = array(
    '#type' => 'item',
    '#title' => t('Versions'),
    '#markup' => theme('item_list', array('items' => $version_strings)),
  );

  return $form;
}
